title: MD ConnectSG
description: Theme by "Minima"  #jekyll
theme: minima  #jekyll Themes selection


header_pages: #Add Navigation Links
  - dashboard.md
  - about.md
  - bookmarks.md
  - projects.md
  - communication.md
